import { StyleSheet } from "react-native";

const baseUnit = 10;

const s = StyleSheet.create({
  mAuto: {
    margin: "auto",
  },
  ma0: { margin: 0 },
  ma05: { margin: 0.5 * baseUnit },
  ma1: { margin: 1 * baseUnit },
  ma15: { margin: 1.5 * baseUnit },
  ma2: { margin: 2 * baseUnit },
  ma25: { margin: 2.5 * baseUnit },
  ma3: { margin: 3 * baseUnit },
  ma35: { margin: 3.5 * baseUnit },
  ma4: { margin: 4 * baseUnit },
  ma45: { margin: 4.5 * baseUnit },
  ma5: { margin: 5 * baseUnit },
  ma55: { margin: 5.5 * baseUnit },
  ma6: { margin: 6 * baseUnit },
  ma65: { margin: 6.5 * baseUnit },
  ma7: { margin: 7 * baseUnit },
  ml0: { marginLeft: 0 },
  ml05: { marginLeft: 0.5 * baseUnit },
  ml1: { marginLeft: 1 * baseUnit },
  ml15: { marginLeft: 1.5 * baseUnit },
  ml2: { marginLeft: 2 * baseUnit },
  ml25: { marginLeft: 2.5 * baseUnit },
  ml3: { marginLeft: 3 * baseUnit },
  ml35: { marginLeft: 3.5 * baseUnit },
  ml4: { marginLeft: 4 * baseUnit },
  ml45: { marginLeft: 4.5 * baseUnit },
  ml5: { marginLeft: 5 * baseUnit },
  ml55: { marginLeft: 5.5 * baseUnit },
  ml6: { marginLeft: 6 * baseUnit },
  ml65: { marginLeft: 6.5 * baseUnit },
  ml7: { marginLeft: 7 * baseUnit },
  mr0: { marginRight: 0 },
  mr05: { marginRight: 0.5 * baseUnit },
  mr1: { marginRight: 1 * baseUnit },
  mr15: { marginRight: 1.5 * baseUnit },
  mr2: { marginRight: 2 * baseUnit },
  mr25: { marginRight: 2.5 * baseUnit },
  mr3: { marginRight: 3 * baseUnit },
  mr35: { marginRight: 3.5 * baseUnit },
  mr4: { marginRight: 4 * baseUnit },
  mr45: { marginRight: 4.5 * baseUnit },
  mr5: { marginRight: 5 * baseUnit },
  mr55: { marginRight: 5.5 * baseUnit },
  mr6: { marginRight: 6 * baseUnit },
  mr65: { marginRight: 6.5 * baseUnit },
  mr7: { marginRight: 7 * baseUnit },
  mt0: { marginTop: 0 },
  mt05: { marginTop: 0.5 * baseUnit },
  mt1: { marginTop: 1 * baseUnit },
  mt15: { marginTop: 1.5 * baseUnit },
  mt2: { marginTop: 2 * baseUnit },
  mt25: { marginTop: 2.5 * baseUnit },
  mt3: { marginTop: 3 * baseUnit },
  mt35: { marginTop: 3.5 * baseUnit },
  mt4: { marginTop: 4 * baseUnit },
  mt45: { marginTop: 4.5 * baseUnit },
  mt5: { marginTop: 5 * baseUnit },
  mt55: { marginTop: 5.5 * baseUnit },
  mt6: { marginTop: 6 * baseUnit },
  mt65: { marginTop: 6.5 * baseUnit },
  mt7: { marginTop: 7 * baseUnit },
  mb0: { marginBottom: 0 },
  mb05: { marginBottom: 0.5 * baseUnit },
  mb1: { marginBottom: 1 * baseUnit },
  mb15: { marginBottom: 1.5 * baseUnit },
  mb2: { marginBottom: 2 * baseUnit },
  mb25: { marginBottom: 2.5 * baseUnit },
  mb3: { marginBottom: 3 * baseUnit },
  mb35: { marginBottom: 3.5 * baseUnit },
  mb4: { marginBottom: 4 * baseUnit },
  mb45: { marginBottom: 4.5 * baseUnit },
  mb5: { marginBottom: 5 * baseUnit },
  mb55: { marginBottom: 5.5 * baseUnit },
  mb6: { marginBottom: 6 * baseUnit },
  mb65: { marginBottom: 6.5 * baseUnit },
  mb7: { marginBottom: 7 * baseUnit },
  my0: { marginTop: 0, marginBottom: 0 },
  my05: { marginTop: 0.5 * baseUnit, marginBottom: 0.5 * baseUnit },
  my1: { marginTop: 1 * baseUnit, marginBottom: 1 * baseUnit },
  my15: { marginTop: 1.5 * baseUnit, marginBottom: 1.5 * baseUnit },
  my2: { marginTop: 2 * baseUnit, marginBottom: 2 * baseUnit },
  my25: { marginTop: 2.5 * baseUnit, marginBottom: 2.5 * baseUnit },
  my3: { marginTop: 3 * baseUnit, marginBottom: 3 * baseUnit },
  my35: { marginTop: 3.5 * baseUnit, marginBottom: 3.5 * baseUnit },
  my4: { marginTop: 4 * baseUnit, marginBottom: 4 * baseUnit },
  my45: { marginTop: 4.5 * baseUnit, marginBottom: 4.5 * baseUnit },
  my5: { marginTop: 5 * baseUnit, marginBottom: 5 * baseUnit },
  my55: { marginTop: 5.5 * baseUnit, marginBottom: 5.5 * baseUnit },
  my6: { marginTop: 6 * baseUnit, marginBottom: 6 * baseUnit },
  my65: { marginTop: 6.5 * baseUnit, marginBottom: 6.5 * baseUnit },
  my7: { marginTop: 7 * baseUnit, marginBottom: 7 * baseUnit },
  mx0: { marginLeft: 0, marginRight: 0 },
  mx05: { marginLeft: 0.5 * baseUnit, marginRight: 0.5 * baseUnit },
  mx1: { marginLeft: 1 * baseUnit, marginRight: 1 * baseUnit },
  mx15: { marginLeft: 1.5 * baseUnit, marginRight: 1.5 * baseUnit },
  mx2: { marginLeft: 2 * baseUnit, marginRight: 2 * baseUnit },
  mx25: { marginLeft: 2.5 * baseUnit, marginRight: 2.5 * baseUnit },
  mx3: { marginLeft: 3 * baseUnit, marginRight: 3 * baseUnit },
  mx35: { marginLeft: 3.5 * baseUnit, marginRight: 3.5 * baseUnit },
  mx4: { marginLeft: 4 * baseUnit, marginRight: 4 * baseUnit },
  mx45: { marginLeft: 4.5 * baseUnit, marginRight: 4.5 * baseUnit },
  mx5: { marginLeft: 5 * baseUnit, marginRight: 5 * baseUnit },
  mx55: { marginLeft: 5.5 * baseUnit, marginRight: 5.5 * baseUnit },
  mx6: { marginLeft: 6 * baseUnit, marginRight: 6 * baseUnit },
  mx65: { marginLeft: 6.5 * baseUnit, marginRight: 6.5 * baseUnit },
  mx7: { marginLeft: 7 * baseUnit, marginRight: 7 * baseUnit },
  pa0: { padding: 0 },
  pa05: { padding: 0.5 * baseUnit },
  pa1: { padding: 1 * baseUnit },
  pa15: { padding: 1.5 * baseUnit },
  pa2: { padding: 2 * baseUnit },
  pa25: { padding: 2.5 * baseUnit },
  pa3: { padding: 3 * baseUnit },
  pa35: { padding: 3.5 * baseUnit },
  pa4: { padding: 4 * baseUnit },
  pa45: { padding: 4.5 * baseUnit },
  pa5: { padding: 5 * baseUnit },
  pa55: { padding: 5.5 * baseUnit },
  pa6: { padding: 6 * baseUnit },
  pa65: { padding: 6.5 * baseUnit },
  pa7: { padding: 7 * baseUnit },
  pb0: { paddingBottom: 0 },
  pb05: { paddingBottom: 0.5 * baseUnit },
  pb1: { paddingBottom: 1 * baseUnit },
  pb15: { paddingBottom: 1.5 * baseUnit },
  pb2: { paddingBottom: 2 * baseUnit },
  pb25: { paddingBottom: 2.5 * baseUnit },
  pb3: { paddingBottom: 3 * baseUnit },
  pb35: { paddingBottom: 3.5 * baseUnit },
  pb4: { paddingBottom: 4 * baseUnit },
  pb45: { paddingBottom: 4.5 * baseUnit },
  pb5: { paddingBottom: 5 * baseUnit },
  pb55: { paddingBottom: 5.5 * baseUnit },
  pb6: { paddingBottom: 6 * baseUnit },
  pb65: { paddingBottom: 6.5 * baseUnit },
  pb7: { paddingBottom: 7 * baseUnit },
  pr0: { paddingRight: 0 },
  pr05: { paddingRight: 0.5 * baseUnit },
  pr1: { paddingRight: 1 * baseUnit },
  pr15: { paddingRight: 1.5 * baseUnit },
  pr2: { paddingRight: 2 * baseUnit },
  pr25: { paddingRight: 2.5 * baseUnit },
  pr3: { paddingRight: 3 * baseUnit },
  pr35: { paddingRight: 3.5 * baseUnit },
  pr4: { paddingRight: 4 * baseUnit },
  pr45: { paddingRight: 4.5 * baseUnit },
  pr5: { paddingRight: 5 * baseUnit },
  pr55: { paddingRight: 5.5 * baseUnit },
  pr6: { paddingRight: 6 * baseUnit },
  pr65: { paddingRight: 6.5 * baseUnit },
  pr7: { paddingRight: 7 * baseUnit },
  pl0: { paddingLeft: 0 },
  pl05: { paddingLeft: 0.5 * baseUnit },
  pl1: { paddingLeft: 1 * baseUnit },
  pl15: { paddingLeft: 1.5 * baseUnit },
  pl2: { paddingLeft: 2 * baseUnit },
  pl25: { paddingLeft: 2.5 * baseUnit },
  pl3: { paddingLeft: 3 * baseUnit },
  pl35: { paddingLeft: 3.5 * baseUnit },
  pl4: { paddingLeft: 4 * baseUnit },
  pl45: { paddingLeft: 4.5 * baseUnit },
  pl5: { paddingLeft: 5 * baseUnit },
  pl55: { paddingLeft: 5.5 * baseUnit },
  pl6: { paddingLeft: 6 * baseUnit },
  pl65: { paddingLeft: 6.5 * baseUnit },
  pl7: { paddingLeft: 7 * baseUnit },
  pt0: { paddingTop: 0 },
  pt05: { paddingTop: 0.5 * baseUnit },
  pt1: { paddingTop: 1 * baseUnit },
  pt15: { paddingTop: 1.5 * baseUnit },
  pt2: { paddingTop: 2 * baseUnit },
  pt25: { paddingTop: 2.5 * baseUnit },
  pt3: { paddingTop: 3 * baseUnit },
  pt35: { paddingTop: 3.5 * baseUnit },
  pt4: { paddingTop: 4 * baseUnit },
  pt45: { paddingTop: 4.5 * baseUnit },
  pt5: { paddingTop: 5 * baseUnit },
  pt55: { paddingTop: 5.5 * baseUnit },
  pt6: { paddingTop: 6 * baseUnit },
  pt65: { paddingTop: 6.5 * baseUnit },
  pt7: { paddingTop: 7 * baseUnit },
  px0: { paddingLeft: 0, paddingRight: 0 },
  px05: { paddingLeft: 0.5 * baseUnit, paddingRight: 0.5 * baseUnit },
  px1: { paddingLeft: 1 * baseUnit, paddingRight: 1 * baseUnit },
  px15: { paddingLeft: 1.5 * baseUnit, paddingRight: 1.5 * baseUnit },
  px2: { paddingLeft: 2 * baseUnit, paddingRight: 2 * baseUnit },
  px25: { paddingLeft: 2.5 * baseUnit, paddingRight: 2.5 * baseUnit },
  px3: { paddingLeft: 3 * baseUnit, paddingRight: 3 * baseUnit },
  px35: { paddingLeft: 3.5 * baseUnit, paddingRight: 3.5 * baseUnit },
  px4: { paddingLeft: 4 * baseUnit, paddingRight: 4 * baseUnit },
  px45: { paddingLeft: 4.5 * baseUnit, paddingRight: 4.5 * baseUnit },
  px5: { paddingLeft: 5 * baseUnit, paddingRight: 5 * baseUnit },
  px55: { paddingLeft: 5.5 * baseUnit, paddingRight: 5.5 * baseUnit },
  px6: { paddingLeft: 6 * baseUnit, paddingRight: 6 * baseUnit },
  px65: { paddingLeft: 6.5 * baseUnit, paddingRight: 6.5 * baseUnit },
  px7: { paddingLeft: 7 * baseUnit, paddingRight: 7 * baseUnit },
  py0: { paddingTop: 0, paddingBottom: 0 },
  py05: { paddingTop: 0.5 * baseUnit, paddingBottom: 0.5 * baseUnit },
  py1: { paddingTop: 1 * baseUnit, paddingBottom: 1 * baseUnit },
  py15: { paddingTop: 1.5 * baseUnit, paddingBottom: 1.5 * baseUnit },
  py2: { paddingTop: 2 * baseUnit, paddingBottom: 2 * baseUnit },
  py25: { paddingTop: 2.5 * baseUnit, paddingBottom: 2.5 * baseUnit },
  py3: { paddingTop: 3 * baseUnit, paddingBottom: 3 * baseUnit },
  py35: { paddingTop: 3.5 * baseUnit, paddingBottom: 3.5 * baseUnit },
  py4: { paddingTop: 4 * baseUnit, paddingBottom: 4 * baseUnit },
  py45: { paddingTop: 4.5 * baseUnit, paddingBottom: 4.5 * baseUnit },
  py5: { paddingTop: 5 * baseUnit, paddingBottom: 5 * baseUnit },
  py55: { paddingTop: 5.5 * baseUnit, paddingBottom: 5.5 * baseUnit },
  py6: { paddingTop: 6 * baseUnit, paddingBottom: 6 * baseUnit },
  py65: { paddingTop: 6.5 * baseUnit, paddingBottom: 6.5 * baseUnit },
  py7: { paddingTop: 7 * baseUnit, paddingBottom: 7 * baseUnit },
  fs0: { fontSize: 0 },
  fs08: { fontSize: 12.8 }, // Assuming 1rem = 16px
  fs1: { fontSize: 16 },
  fs125: { fontSize: 20 },
  fs15: { fontSize: 24 },
  fs2: { fontSize: 32 },
  fs25: { fontSize: 40 },
  fs3: { fontSize: 48 },
  fs35: { fontSize: 56 },
  fs4: { fontSize: 64 },
  fs45: { fontSize: 72 },
  fs5: { fontSize: 80 },
  fs55: { fontSize: 88 },
  fs6: { fontSize: 96 },
  fs65: { fontSize: 104 },
  fs7: { fontSize: 112 },
  fw400: { fontWeight: "400" },
  fw600: { fontWeight: "600" },
  fw800: { fontWeight: "800" },
  fw900: { fontWeight: "900" },
  fsItalic: { fontStyle: "italic" },
  taLeft: { textAlign: "left" },
  taRight: { textAlign: "right" },
  taCenter: { textAlign: "center" },
  tdUnderline: { textDecorationLine: "underline" },
  tdNone: { textDecorationLine: "none" },
  ttUppercase: { textTransform: "uppercase" },
  ttLowercase: { textTransform: "lowercase" },
  ttCapitalize: { textTransform: "capitalize" },
  w0: { width: 0 },
  w05: { width: baseUnit * 0.5 },
  w1: { width: baseUnit },
  w15: { width: baseUnit * 1.5 },
  w2: { width: baseUnit * 2 },
  w25: { width: baseUnit * 2.5 },
  w3: { width: baseUnit * 3 },
  w35: { width: baseUnit * 3.5 },
  w4: { width: baseUnit * 4 },
  w45: { width: baseUnit * 4.5 },
  w5: { width: baseUnit * 5 },
  w55: { width: baseUnit * 5.5 },
  w6: { width: baseUnit * 6 },
  w65: { width: baseUnit * 6.5 },
  w7: { width: baseUnit * 7 },
  w8: { width: baseUnit * 8 },
  w9: { width: baseUnit * 9 },
  w10: { width: baseUnit * 10 },
  w11: { width: baseUnit * 11 },
  w12: { width: baseUnit * 12 },
  w13: { width: baseUnit * 13 },
  w14: { width: baseUnit * 14 },
  w15: { width: baseUnit * 15 },
  w16: { width: baseUnit * 16 },
  w17: { width: baseUnit * 17 },
  w18: { width: baseUnit * 18 },
  w19: { width: baseUnit * 19 },
  w20: { width: baseUnit * 20 },
  w21: { width: baseUnit * 21 },
  w22: { width: baseUnit * 22 },
  w23: { width: baseUnit * 23 },
  w24: { width: baseUnit * 24 },
  w25: { width: baseUnit * 25 },
  minW0: { minWidth: 0 },
  minW05: { minWidth: baseUnit * 0.5 },
  minW1: { minWidth: baseUnit },
  minW15: { minWidth: baseUnit * 1.5 },
  minW2: { minWidth: baseUnit * 2 },
  minW25: { minWidth: baseUnit * 2.5 },
  minW3: { minWidth: baseUnit * 3 },
  minW35: { minWidth: baseUnit * 3.5 },
  minW4: { minWidth: baseUnit * 4 },
  minW45: { minWidth: baseUnit * 4.5 },
  minW5: { minWidth: baseUnit * 5 },
  minW55: { minWidth: baseUnit * 5.5 },
  minW6: { minWidth: baseUnit * 6 },
  minW65: { minWidth: baseUnit * 6.5 },
  minW7: { minWidth: baseUnit * 7 },
  maxW0: { maxWidth: 0 },
  maxW05: { maxWidth: baseUnit * 0.5 },
  maxW1: { maxWidth: baseUnit },
  maxW15: { maxWidth: baseUnit * 1.5 },
  maxW2: { maxWidth: baseUnit * 2 },
  maxW25: { maxWidth: baseUnit * 2.5 },
  maxW3: { maxWidth: baseUnit * 3 },
  maxW35: { maxWidth: baseUnit * 3.5 },
  maxW4: { maxWidth: baseUnit * 4 },
  maxW45: { maxWidth: baseUnit * 4.5 },
  maxW5: { maxWidth: baseUnit * 5 },
  maxW55: { maxWidth: baseUnit * 5.5 },
  maxW6: { maxWidth: baseUnit * 6 },
  maxW65: { maxWidth: baseUnit * 6.5 },
  maxW7: { maxWidth: baseUnit * 7 },
  maxW10: { maxWidth: baseUnit * 10 },
  maxW15: { maxWidth: baseUnit * 15 },
  maxW20: { maxWidth: baseUnit * 20 },
  maxW25: { maxWidth: baseUnit * 25 },
  maxW30: { maxWidth: baseUnit * 30 },
  maxW35: { maxWidth: baseUnit * 35 },
  maxW40: { maxWidth: baseUnit * 40 },
  maxW45: { maxWidth: baseUnit * 45 },
  maxW50: { maxWidth: baseUnit * 50 },
  h0: { height: 0 },
  h05: { height: baseUnit * 0.5 },
  h1: { height: baseUnit },
  h15: { height: baseUnit * 1.5 },
  h2: { height: baseUnit * 2 },
  h25: { height: baseUnit * 2.5 },
  h3: { height: baseUnit * 3 },
  h35: { height: baseUnit * 3.5 },
  h4: { height: baseUnit * 4 },
  h45: { height: baseUnit * 4.5 },
  h5: { height: baseUnit * 5 },
  h55: { height: baseUnit * 5.5 },
  h6: { height: baseUnit * 6 },
  h65: { height: baseUnit * 6.5 },
  h7: { height: baseUnit * 7 },
  h25p: { height: "25%" },
  h50p: { height: "50%" },
  h75p: { height: "75%" },
  h100p: { height: "100%" },

  minH0: { minHeight: 0 },
  minH05: { minHeight: baseUnit * 0.5 },
  minH1: { minHeight: baseUnit },
  minH15: { minHeight: baseUnit * 1.5 },
  minH2: { minHeight: baseUnit * 2 },
  minH25: { minHeight: baseUnit * 2.5 },
  minH3: { minHeight: baseUnit * 3 },
  minH35: { minHeight: baseUnit * 3.5 },
  minH4: { minHeight: baseUnit * 4 },
  minH45: { minHeight: baseUnit * 4.5 },
  minH5: { minHeight: baseUnit * 5 },
  minH55: { minHeight: baseUnit * 5.5 },
  minH6: { minHeight: baseUnit * 6 },
  minH65: { minHeight: baseUnit * 6.5 },
  minH7: { minHeight: baseUnit * 7 },
  minH25p: { minHeight: "25%" },
  minH50p: { minHeight: "50%" },
  minH75p: { minHeight: "75%" },
  minH100p: { minHeight: "100%" },

  maxH0: { maxHeight: 0 },
  maxH05: { maxHeight: baseUnit * 0.5 },
  maxH1: { maxHeight: baseUnit },
  maxH15: { maxHeight: baseUnit * 1.5 },
  maxH2: { maxHeight: baseUnit * 2 },
  maxH25: { maxHeight: baseUnit * 2.5 },
  maxH3: { maxHeight: baseUnit * 3 },
  maxH35: { maxHeight: baseUnit * 3.5 },
  maxH4: { maxHeight: baseUnit * 4 },
  maxH45: { maxHeight: baseUnit * 4.5 },
  maxH5: { maxHeight: baseUnit * 5 },
  maxH55: { maxHeight: baseUnit * 5.5 },
  maxH6: { maxHeight: baseUnit * 6 },
  maxH65: { maxHeight: baseUnit * 6.5 },
  maxH7: { maxHeight: baseUnit * 7 },
  maxH25p: { maxHeight: "25%" },
  maxH50p: { maxHeight: "50%" },
  maxH75p: { maxHeight: "75%" },
  maxH100p: { maxHeight: "100%" },
  df: {
    display: "flex",
  },
  dn: {
    display: "none",
  },
  jcsb: {
    justifyContent: "space-between",
  },
  jcsa: {
    justifyContent: "space-around",
  },
  jcse: {
    justifyContent: "space-evenly",
  },
  o25: {
    opacity: 0.25,
  },
  o50: {
    opacity: 0.5,
  },
  o75: {
    opacity: 0.75,
  },
  o1: {
    opacity: 1,
  },
  oh: {
    overflow: "hidden",
  },
  fdr: {
    flexDirection: "row",
  },
  b1: {
    border: "1px solid ",
  },
  b2: {
    border: "1px solid ",
  },
  b3: {
    border: "1px solid ",
  },
  b4: {
    border: "1px solid ",
  },
  b5: {
    border: "1px solid ",
  },
  br5: {
    borderRadius: "5px",
  },
  br10: {
    borderRadius: 1 * baseUnit,
  },
  br20: {
    borderRadius: 2 * baseUnit,
  },
  br50: {
    borderRadius: "50%",
  },
  bcw: {
    backgroundColor: "white",
  },
  cw: {
    color: "white",
    fill: "white",
  },
  cb: {
    color: "black",
    fill: "black",
  },
  aic: {
    alignItems: "center",
  },
  g1: {
    gap: 1 * baseUnit,
  },
  g2: {
    gap: 2 * baseUnit,
  },
  g3: {
    gap: 3 * baseUnit,
  },
  g4: {
    gap: 4 * baseUnit,
  },
  g5: {
    gap: 5 * baseUnit,
  },
  ar: {
    aspectRatio: 1,
  },
  bcg: {
    backgroundColor: "#EBEBEB",
  },
  fdr: {
    flexDirection: "row",
  },
});

export default s;
